INSERT INTO ROLES (ROLE) VALUES ('guest');
INSERT INTO ROLES (ROLE) VALUES ('user');
INSERT INTO ROLES (ROLE) VALUES ('administrator');

INSERT INTO USERS (NAME, SURNAME, EMAIL, AGE)
VALUES ('Ivan', 'Ivanov', 'vanya@gmail.com', '23');
INSERT INTO USERS (NAME, SURNAME, EMAIL, AGE)
VALUES ('Peter', 'Petrov', 'petya@gmail.com', '23');
INSERT INTO USERS (NAME, SURNAME, EMAIL, AGE)
VALUES ('bill', 'smit', 'smit@gmail.com', '33');

INSERT INTO AUTHENTICATE (LOGIN, PASSWORD, PROFILE_ENABLE) VALUES ('admin1', '1', 'true');
INSERT INTO AUTHENTICATE (LOGIN, PASSWORD, PROFILE_ENABLE) VALUES ('admin2', '1', 'true');
INSERT INTO AUTHENTICATE (LOGIN, PASSWORD, PROFILE_ENABLE) VALUES ('user', '1', 'true');

INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES ('1', '3');
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES ('2', '3');
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES ('3', '2');

INSERT INTO BASKETS (USER_ID) values ('1');
INSERT INTO BASKETS (USER_ID) values ('2');
INSERT INTO BASKETS (USER_ID) values ('3');

INSERT INTO BOOKS (AUTHOR, TITLE, PAGES) VALUES ( 'Arthur Haily', 'Airport', '5');
INSERT INTO BOOKS (AUTHOR, TITLE, PAGES) VALUES ( 'Korney Chukovskiy', 'Aibolit', '4');
INSERT INTO BOOKS (AUTHOR, TITLE, PAGES) VALUES ( 'Korney Chukovskiy', 'Aibolit', '4');
INSERT INTO BOOKS (AUTHOR, TITLE, PAGES) VALUES ( 'Korney Chukovskiy', 'Moidodyr', '8');
INSERT INTO BOOKS (AUTHOR, TITLE, PAGES) VALUES ( 'Korney Chukovskiy', 'Tarakanishche', '3');


